valid token may not have subject field
infobloxopen/atlas-app-toolkit pull request #230
Opened 2021-03-03 13:33 UTC by binjip978

2021-03-03 14:13 UTC, addudko commented on logging/interceptor.go
> +			// non client token does not have subject ingore
```suggestion
			// non client token does not have subject field, ignore
```

2021-03-03 14:31 UTC, addudko approved these changes

2021-03-03 18:00 UTC, drewwells requested changes

2021-03-03 18:00 UTC, drewwells commented on logging/interceptor.go
> +
Updates to this project need PR tests. Please add a unit test verifying what this functionality does

2021-03-05 13:04 UTC, Evgeniy-L approved these changes
Looks good

2021-03-19 16:21 UTC, drewwells approved these changes
Thanks for unit test! sorry on slow review

2021-03-22 06:44 UTC, merged